### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MagicAndre1981** [icnocop/PackageReferenceVersionToAttribute#1]
The extension doesn't work for me. I see in the output pane that it was successful, I see the created csproj.bak file, but the .bak and the csproj are identical.

In my csproj files I have a mix of both types

```
  <PackageReference Include="Newtonsoft.Json">
    <Version>13.0.3</Version>
  </PackageReference>
```

and

`<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />`

and mabye this confuses the extension. I want all references to be the 1 line one, this is why I tried your extension.

**Comment by icnocop** [comment]
Hi.

Thank you for reporting this issue.

Unfortunately, I'm not able to reproduce the issue.

Here are the steps I tried:
1. Clone this repository
2. Open src\DemoLibrary.sln
3. Edit DemoLibrary.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
```
4. Right-click `DemoLibrary` in `Solution Explorer` and select `Convert PackageReference Version elements to attributes...`.
5. Status bar indicates `Conversion completed successfully`
6. `PackageReference Version to attribute` output window displays `INFO: Conversion completed successfully.`
7. DemoLibrary.csproj was successfully updated to:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
```

Can you provide a project file that can reproduce the issue?

Thank you.

**Comment by MagicAndre1981** [comment]
ok, I copied the entries from my not working project into a demo solution and here it worked:

![image](https://github.com/user-attachments/assets/8b5668f3-2d24-4a9e-9e54-43f60f94f4ab)

I'll do some more testings

**Comment by MagicAndre1981** [comment]
ok, it fails with a new blank UWP project with those references in different styles.

```
<ItemGroup>
    <PackageReference Include="Acr.UserDialogs">
      <Version>7.2.0.564</Version>
    </PackageReference>
    <PackageReference Include="Coding4Fun.Toolkit.Controls">
      <Version>2.1.8</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces">
      <Version>8.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Bcl.TimeProvider">
      <Version>8.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.2.14" />
    <PackageReference Include="Microsoft.UI.Xaml">
      <Version>2.8.6</Version>
    </PackageReference>
    <PackageReference Include="SmartFormat.NET" Version="3.5.1" />
    <PackageReference Include="Syncfusion.Licensing">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.SfInput.UWP">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.SfShared.UWP">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.Xamarin.Core">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.Xamarin.GridCommon">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.Xamarin.SfComboBox">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.Xamarin.SfDataGrid">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="Syncfusion.Xamarin.SfNumericTextBox">
      <Version>27.1.57</Version>
    </PackageReference>
    <PackageReference Include="System.Buffers">
      <Version>4.5.1</Version>
    </PackageReference>
    <PackageReference Include="System.IO.Pipelines">
      <Version>8.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.5.5</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Tasks.Extensions">
      <Version>4.5.4</Version>
    </PackageReference>
    <PackageReference Include="Win2D.uwp">
      <Version>1.28.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.8.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms">
      <Version>5.0.0.2662</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.HotReload">
      <Version>1.6.1</Version>
    </PackageReference>
    <PackageReference Include="ZString">
      <Version>2.6.0</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by MagicAndre1981** [comment]
On a real solution it now worked for only 1 csproj of 29 csproj files in the solution and output always shows success:

`INFO: Conversion completed successfully.`

**Comment by MagicAndre1981** [comment]
on a 2nd  and 3rd VM, the tool doesn't convert any csproj. So I tried 17.10 LTSC, 17.11 Current and 17.12 Preview 5 and it only worked for 1 project .

I use Subversion as source control, maybe this is an issue with checkout. I have VisualSVN in VS2022 installed.

**Comment by MagicAndre1981** [comment]
and my added dedug code shows this:

`DEBUG: packageReferences Count(): 0`

So the [foreach is skipped](https://github.com/icnocop/PackageReferenceVersionToAttribute/blob/b7f56287fba4ba0daf9a4134a1e26a267eda88c7/src/PackageReferenceVersionToAttributeExtension/Commands/ConvertPackageReferenceVersionElementsToAttributesCommand.cs#L96)

because your [query returns nothing](https://github.com/icnocop/PackageReferenceVersionToAttribute/blob/b7f56287fba4ba0daf9a4134a1e26a267eda88c7/src/PackageReferenceVersionToAttributeExtension/Commands/ConvertPackageReferenceVersionElementsToAttributesCommand.cs#L92) for a csprj that has entries with Version:

  ```
  <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="EntityFramework.Firebird" Version="10.0.1" />
    <PackageReference Include="Enums.NET">
      <Version>5.0.0</Version>
    </PackageReference>
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.1" />
    <PackageReference Include="MathNet.Numerics.Signed">
      <Version>5.0.0</Version>
    </PackageReference>
```

**Comment by icnocop** [comment]
Does your project file have an XML namespace?

For example,
```
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
</Project>
````

I've updated the code to support converting projects with an XML namespace.

Please update the Visual Studio extension to v1.0.1101.15 and then try again.

Thank you.

**Comment by MagicAndre1981** [comment]
ok, now the UWP project got converted and I see in the new project that the top line was removed from csproj in generated files:

`<?xml version="1.0" encoding="utf-8"?>`

Was this causing my issue?

I use a mix of old csproj files and net net sdk style csprojs. Looks like it works now more reliable.  I'll test it more when the multiple/all converting is added to offical build and try it on more solutions.

**Comment by icnocop** [comment]
The XML declaration was not causing the issue, it was the XML namespace.

The latest version now preserves the XML declaration if it exists, and does not remove it.

Please update to v1.0.1102.24 or higher.

Thank you.

**Comment by MagicAndre1981** [comment]
> Please update to v1.0.1102.24 or higher.

new version fails to load, see #5

**Comment by icnocop** [comment]
Thank you for testing.

I just pushed another update to resolve this error.

Please update the extension to v1.0.1103.27.

Thank you.

**Comment by MagicAndre1981** [comment]
new version works now.
