### ISSUE TITLE
dotnet tool

### ISSUE THREAD

**Issue by MagicAndre1981** [icnocop/PackageReferenceVersionToAttribute#3]
It would be nice to split the core functionality and ui to allow other clients to be created. I think of a [dotnet tool ](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)for example to be able to convert the references from command line.

**Comment by icnocop** [comment]
A dotnet tool was published with the name `PackageReferenceVersionToAttribute.Tool`.

See [Getting started with the dotnet tool](https://github.com/icnocop/PackageReferenceVersionToAttribute?tab=readme-ov-file#getting-started-with-the-dotnet-tool) from README.md.

Thank you.

**Comment by MagicAndre1981** [comment]
works fine for a csproj, bonus would be to allow passing sln as parameter to also convert all csprojs in 1 run (currently you get `System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1` when passing a sln as parameter)

**Comment by icnocop** [comment]
The latest preview version now has support for converting `csproj` project files within `sln` solution files on the command line:

`PackageReferenceVersionToAttribute.Tool` `1.0.1104-build-35`

**Comment by MagicAndre1981** [comment]
works, but the versions are confusing. [1.0.1104-build-36](https://www.nuget.org/packages/PackageReferenceVersionToAttribute.Tool/1.0.1104-build-36) is newer, but `dotnet tool install` complains about lower version, so I had to force it:

`dotnet tool install --global PackageReferenceVersionToAttribute.Tool --version 1.0.1104-build-36 --allow-downgrade`

Now it works for slns, too.

Btw, Microsoft now works on a new sln format called slnx, keep this in mind to update the lib later when this format will be stable (likely in 17.14 update with the slnx parsing lib `Microsoft.VisualStudio.SolutionPersistence`)

**Comment by icnocop** [comment]
I just released v1.0.1105.

Thank you.
