### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by MagicAndre1981** [icnocop/PackageReferenceVersionToAttribute#4]
Currently you [only support normal x64](https://github.com/icnocop/PackageReferenceVersionToAttribute/blob/ea01a157296efc709c4a6df971295034a10dae01/src/PackageReferenceVersionToAttributeExtension/source.extension.vsixmanifest#L15), but users of the new **Snapdragon X Elite** with [Windows 11 on ARM](https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022) may also want to use the extension, so adding arm64 support would be nice.

**Comment by icnocop** [comment]
The latest version now allows installing on Visual Studio 2022 Arm64.

Please try v1.0.1102.24 or higher.

Thank you.

**Comment by MagicAndre1981** [comment]
I don't have ARM64 HW, but it looks good
